module.exports = {
  content: ["./src/**/*.{html,js}", "./index.html"],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '976px',
      xl: '1440px',
    },
    colors: {
      'blue': '#1fb6ff',
      'blue-dark': '#0068b7',
      'blue-light': '#ddf0ff',
      'blue-lighter': '#f0f7ff',
      'purple': '#7e5bef',
      'pink': '#ff49db',
      'orange': '#ff7849',
      'green': '#13ce66',
      'yellow': '#ffc82c',
      'white': '#ffffff',
      'gray-dark': '#273444',
      'gray': '#8492a6',
      'gray-lighter': '#f5f5f7',
      'gray-light': '#d3dce6',
      'green-dark': '#006766',
      'green': '#00a3a3',
      'green-light': '#e6fffa',
      'green-lighter': '#f0fff4',
      'black': '#000000',
      'red': '#ff0000',
      'red-light': '#ffcccc',
      'red-lighter': '#ffe6e6',
      'red-dark': '#990000',
    },
    fontFamily: {
      sans: ['Graphik', 'sans-serif'],
      serif: ['Merriweather', 'serif'],
    },
    extend: {
      spacing: {
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        '4xl': '2rem',
      },
    },
  },
  plugins: [],
};